enrichment:
  confidence_threshold: 0.8
  enabled: true
  quality: premium
environment: production
llm_client:
  api_key: ${LLM_API_KEY}
  endpoint: https://api.groq.com/openai/v1/chat/completions
  model: llama3-70b-8192
  retries: 3
  timeout: 60
logging:
  format: structured
  level: INFO
monitoring:
  enabled: true
  metrics: true
output:
  format: json
  include_metadata: true
  output_dir: outputs
