"""
Pydantic models for capability structures in AutoMCP.

These models define the structure and validation for capabilities
generated by the semantic enrichment process.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from enum import Enum


class CapabilityType(str, Enum):
    """Types of capabilities."""
    
    DATA_RETRIEVAL = "data_retrieval"
    DATA_MODIFICATION = "data_modification"
    COMPUTATION = "computation"
    INTEGRATION = "integration"
    AUTOMATION = "automation"
    ANALYSIS = "analysis"


class Capability(BaseModel):
    """Model for API capability representation."""
    
    id: str = Field(..., description="Unique capability identifier")
    name: str = Field(..., description="Human-readable capability name")
    type: CapabilityType = Field(..., description="Type of capability")
    description: str = Field(..., description="Detailed capability description")
    endpoints: List[str] = Field(..., description="Associated endpoint paths")
    complexity: int = Field(default=1, ge=1, le=10, description="Complexity score (1-10)")
    dependencies: List[str] = Field(default_factory=list, description="Capability dependencies")
    
    # Business value metrics
    business_value: Optional[str] = Field(None, description="Business value description")
    use_cases: List[str] = Field(default_factory=list, description="Common use cases")
    user_personas: List[str] = Field(default_factory=list, description="Target user personas")
    
    # Technical metadata
    required_permissions: List[str] = Field(default_factory=list, description="Required permissions")
    rate_limits: Optional[Dict[str, Any]] = Field(None, description="Rate limiting information")
    data_sensitivity: Optional[str] = Field(None, description="Data sensitivity level")


class CapabilityGroup(BaseModel):
    """Model for grouping related capabilities."""
    
    name: str = Field(..., description="Group name")
    description: str = Field(..., description="Group description")
    capabilities: List[Capability] = Field(..., description="Capabilities in this group")
    priority: int = Field(default=1, ge=1, le=10, description="Group priority")


__all__ = [
    "CapabilityType",
    "Capability",
    "CapabilityGroup"
]
