# =============================================================================
# AutoMCP Development Configuration
# =============================================================================
# Development-friendly settings with enhanced debugging and relaxed validation
# Inherits from default.yaml and overrides for development workflow

environment: "development"
profile: "development"

# =============================================================================
# Development LLM Configuration - Enhanced for Testing
# =============================================================================
llm_client:
  provider_settings:
    groq:
      max_tokens: 2000    # Larger context for development testing
      temperature: 0.3    # Higher temperature for more creative responses
      optimal_batch_size: 4  # Smaller batches for development
      rate_limit_requests_per_minute: 60

# =============================================================================
# Development Parser Configuration - Enhanced
# =============================================================================
parser_workers: 8
parsers:
  workers: 8
  timeout: 60  # Longer timeout for development debugging

# =============================================================================
# Development Semantic Transformation - Enhanced Prompts
# =============================================================================
semantic_transformation:
  llm_prompts:
    intent_generation: |
      Generate a rich semantic intent for this API endpoint (DEVELOPMENT MODE):
      Method: {method}
      Path: {path}
      Summary: {summary}
      Domain: {domain_context}

      Include:
      - Meaningful name
      - Detailed summary
      - Complexity assessment (simple/moderate/complex)
      - User context
      - Business context
      - Security requirements
      - Permission levels (white/grey/black)
      
      Response should be enterprise-grade with clear context and implications.
      Add development-specific debugging information where helpful.

    tool_generation: |
      Create an MCP tool definition for this API endpoint (DEVELOPMENT MODE):
      Method: {method}
      Path: {path}
      Parameters: {parameters}
      Domain: {domain_context}

      Include:
      - Clear, detailed description
      - Comprehensive safety level assessment
      - Complete parameter schema with types
      - Required vs optional fields
      - Rich metadata (complexity, confidence)
      - Detailed parameter descriptions
      - Usage examples where helpful
      - Development debugging hints

# =============================================================================
# Development Enrichment - Relaxed Settings
# =============================================================================
enrichment:
  batch_size: 4
  max_batch_size: 12
  timeout_seconds: 60
  retry_attempts: 5  # More retries for development testing
  use_memory: false

# =============================================================================
# Development Output - Enhanced Debugging
# =============================================================================
output:
  strict_validation: false  # Relaxed validation for development
  quality_assessment:
    enabled: true
    generate_report: true
    min_acceptable_score: 50  # Lower threshold for development
    use_llm_assessment: true
    sampling_rate: 1.0

# =============================================================================
# Development Logging - Verbose
# =============================================================================
logging:
  level: DEBUG  # More verbose logging for development
  format: "console"

# =============================================================================
# Development Validation - Relaxed
# =============================================================================
validation:
  strict: false  # Relaxed validation for development testing

# =============================================================================
# Development Security - Minimal
# =============================================================================
security:
  encrypt_outputs: false  # No encryption needed in development
  input_sanitization: false  # Relaxed for development

# =============================================================================
# Development Error Handling - Enhanced Debugging
# =============================================================================
error_handling:
  max_retries: 5  # More retries for development
  backoff_strategy: "linear"  # Simpler backoff for faster debugging

# =============================================================================
# Development Monitoring - Enhanced
# =============================================================================
monitoring:
  metrics_enabled: true
  log_sampling_rate: 1.0  # Log everything in development
