environment: enterprise
llm_client:
  provider: groq
  endpoint: https://api.groq.com/openai/v1/chat/completions
  model: llama-3.1-8b-instant
  temperature: 0.05  # Lowest temperature for most consistent, deterministic responses
  max_tokens:
    intent: 1500
    tool: 2000
  rate_limits:
    requests_per_minute: 240
    request_delay: 0.25

semantic_transformation:
  llm_prompts:
    intent_generation: |
      Generate an enterprise-grade semantic intent for this API endpoint:
      Method: {method}
      Path: {path}
      Summary: {summary}
      Domain: {domain_context}

      Enterprise requirements:
      1. Strategic business-aligned name
      2. Comprehensive technical summary
      3. Detailed complexity analysis
      4. Role-based access context
      5. Enterprise security requirements
      6. Granular permission matrix
      7. Compliance implications
      8. Data governance aspects
      9. SLA/Performance requirements
      10. Integration touchpoints

      Format: Enterprise-grade, audit-ready output

    tool_generation: |
      Create an enterprise-grade MCP tool definition:
      Method: {method}
      Path: {path}
      Parameters: {parameters}
      Domain: {domain_context}

      Enterprise requirements:
      1. Enterprise context description
      2. Full security assessment
      3. Complete parameter validation
      4. Enterprise validation rules
      5. Performance SLAs
      6. Compliance metadata
      7. Rate limiting policies
      8. Security controls
      9. Audit requirements
      10. Data classification

      Format: Enterprise-compliant, governance-ready output

logging:
  level: INFO
  format: json
  redact_keys:
    - api_key
    - password
    - token
    - secret
    - credential
    - pii
    - sensitive

security:
  sensitive_data_patterns:
    pii:
      - email
      - phone
      - address
      - ssn
    credentials:
      - password
      - api_key
      - token
      - secret
    business:
      - account_number
      - tax_id
      - contract_id

validation:
  enterprise_rules:
    max_nested_depth: 10
    max_array_items: 1000
    max_string_length: 10000
    required_fields:
      - security_classification
      - data_owner
      - retention_policy
