# =============================================================================
# AutoMCP Enterprise Configuration
# =============================================================================
# Enterprise-grade settings with maximum compliance, security, and governance
# Inherits from default.yaml and overrides for enterprise deployment

environment: "enterprise"
profile: "enterprise"

# =============================================================================
# Enterprise LLM Configuration - Maximum Consistency
# =============================================================================
llm_client:
  provider_settings:
    groq:
      max_tokens: 1500      # Balanced for enterprise needs
      temperature: 0.05     # Lowest temperature for deterministic responses
      optimal_batch_size: 32  # Maximum batches for enterprise throughput
      rate_limit_requests_per_minute: 240

# =============================================================================
# Enterprise Parser Configuration - Maximum Performance
# =============================================================================
parser_workers: 32
parsers:
  workers: 32
  timeout: 30

# =============================================================================
# Enterprise Semantic Transformation - Compliance-Ready Prompts
# =============================================================================
semantic_transformation:
  llm_prompts:
    intent_generation: |
      Generate an enterprise-grade semantic intent for this API endpoint:
      Method: {method}
      Path: {path}
      Summary: {summary}
      Domain: {domain_context}

      Enterprise requirements:
      1. Strategic business-aligned name
      2. Comprehensive technical summary
      3. Detailed complexity analysis
      4. Role-based access context
      5. Enterprise security requirements
      6. Granular permission matrix
      7. Compliance implications
      8. Data governance aspects
      9. SLA/Performance requirements
      10. Integration touchpoints

      Format: Enterprise-grade, audit-ready output

    tool_generation: |
      Create an enterprise-grade MCP tool definition:
      Method: {method}
      Path: {path}
      Parameters: {parameters}
      Domain: {domain_context}

      Enterprise requirements:
      1. Enterprise context description
      2. Full security assessment
      3. Complete parameter validation
      4. Enterprise validation rules
      5. Performance SLAs
      6. Compliance metadata
      7. Rate limiting policies
      8. Security controls
      9. Audit requirements
      10. Data classification

      Format: Enterprise-compliant, governance-ready output

# =============================================================================
# Enterprise Enrichment - Maximum Performance
# =============================================================================
enrichment:
  batch_size: 32
  max_batch_size: 64
  timeout_seconds: 30
  retry_attempts: 3
  use_memory: true  # Enable for enterprise scalability

# =============================================================================
# Enterprise Output - Maximum Validation
# =============================================================================
output:
  strict_validation: true
  quality_assessment:
    enabled: true
    generate_report: true
    min_acceptable_score: 90  # Highest threshold for enterprise
    use_llm_assessment: true
    sampling_rate: 1.0  # Full assessment for enterprise

# =============================================================================
# Enterprise Logging - Audit-Grade
# =============================================================================
logging:
  level: INFO
  format: json
  redact_keys:
    - api_key
    - password
    - token
    - secret
    - credential
    - pii
    - sensitive

# =============================================================================
# Enterprise Security - Maximum Protection
# =============================================================================
security:
  encrypt_outputs: true
  input_sanitization: true
  output_encoding: true
  rate_limit_by_key: true
  sensitive_data_patterns:
    pii:
      - email
      - phone
      - address
      - ssn
    credentials:
      - password
      - api_key
      - token
      - secret
    business:
      - account_number
      - tax_id
      - contract_id

# =============================================================================
# Enterprise Validation - Strictest Rules
# =============================================================================
validation:
  strict: true
  enterprise_rules:
    max_nested_depth: 10
    max_array_items: 1000
    max_string_length: 10000
    required_fields:
      - security_classification
      - data_owner
      - retention_policy

# =============================================================================
# Enterprise Error Handling - Maximum Resilience
# =============================================================================
error_handling:
  max_retries: 3
  backoff_strategy: "exponential"
  circuit_breaker:
    failure_threshold: 3  # Stricter for enterprise
    recovery_timeout: 30
  dead_letter_queue: true

# =============================================================================
# Enterprise Monitoring - Full Compliance
# =============================================================================
monitoring:
  metrics_enabled: true
  health_check_port: 8080
  prometheus_endpoint: "/metrics"
  log_sampling_rate: 1.0  # Full logging for enterprise audit
  slow_query_threshold: 2  # Stricter performance requirements
  tracked_metrics:
    - "requests_total"
    - "requests_duration_seconds"
    - "llm_calls_total"
    - "llm_tokens_used"
    - "errors_total"
    - "cache_hits_total"
    - "quality_scores"
    - "compliance_scores"
    - "security_violations"

# =============================================================================
# Enterprise Telemetry - Full Observability
# =============================================================================
telemetry:
  tracing_enabled: true
  metrics_enabled: true
  otel_endpoint: "http://jaeger:14268"
  service_name: "spec-analyzer-mcp-enterprise"
  span_attributes:
    - "semantic_name"
    - "complexity"
    - "user_context"
    - "permission_level"
    - "confidence_score"
    - "compliance_status"
    - "security_classification"

# =============================================================================
# Enterprise Exporter - Full API Access
# =============================================================================
exporter:
  api_auth: true
  api_port: 8000
  memory_store: "faiss"
