# =============================================================================
# AutoMCP Production Configuration
# =============================================================================
# Optimized for production deployment with performance, security, and reliability

$schema: "../schemas/automcp-config-v1.schema.json"
version: "1.0.0"
environment: "production"

# Inherit from default and override for production
extends: "default.yaml"

# =============================================================================
# Production-Specific Overrides
# =============================================================================

# Optimized logging for production
logging:
  level: "INFO"
  format: "json"  # Structured JSON for log aggregation
  log_progress: false  # Reduce log noise
  profile_performance: false
  
  file:
    enabled: true
    path: "/var/log/automcp/automcp.log"
    max_size: "100MB"
    backup_count: 20
    rotation: "daily"

# Production LLM settings with higher throughput
llm:
  provider: "groq"  # Can be overridden via environment
  model: "llama-3.1-70b-versatile"  # More capable model for production
  
  rate_limits:
    requests_per_minute: 100  # Higher for production
    tokens_per_minute: 100000
    concurrent_requests: 8
  
  timeouts:
    request: 30
    total: 180  # Longer total timeout for complex processing
  
  retries:
    max_attempts: 5  # More retries for reliability
    backoff_factor: 2
    max_wait: 120

# High-performance enrichment settings
enrichment:
  batch_size: 16  # Larger batches for efficiency
  confidence_threshold: 0.8  # Higher confidence required
  
  # Production-optimized caching
  caching:
    enabled: true
    ttl: 3600  # Cache for 1 hour
    max_size: 10000

# Strict validation for production
validation:
  strict: true
  schema_validation: true
  parameter_validation: true
  output_validation: true
  fail_fast: true  # Stop on first validation error

output:
  strict_validation: true
  pretty_print: false  # Compact output for efficiency
  include_examples: true
  include_metadata: false  # Reduce output size
  include_debug_info: false

# Enhanced security for production
security:
  encrypt_outputs: true
  pii_scrubbing: true
  api_auth_required: true
  
  # Enhanced PII patterns for production
  sensitive_patterns:
    high: ["password", "secret", "key", "token", "credit_card", "ssn", "tax_id", "medical_record"]
    medium: ["email", "phone", "address", "profile", "personal_id", "ip_address"]
    low: ["name", "username", "user_id"]
  
  # Encryption settings
  encryption:
    algorithm: "AES-256-GCM"
    key_rotation: true
    key_rotation_interval: "30d"

# Production MCP settings
mcp:
  generate_tools: true
  generate_examples: true
  include_schema_validation: true
  
  tools:
    max_parameters: 20  # Allow more complex tools
    max_nesting_depth: 4
    include_optional_params: true
    optimize_for_size: true

# Performance optimizations
performance:
  # Connection pooling
  connection_pool:
    size: 20
    max_overflow: 30
    timeout: 30
  
  # Caching configuration
  cache:
    enabled: true
    backend: "redis"  # Use Redis for distributed caching
    default_ttl: 3600
    max_memory: "1GB"
  
  # Async processing
  async:
    max_workers: 16
    queue_size: 1000
    timeout: 300

# Monitoring and observability
monitoring:
  enabled: true
  metrics:
    prometheus: true
    custom_metrics: true
  
  health_checks:
    enabled: true
    interval: 30
    timeout: 10
  
  tracing:
    enabled: true
    sample_rate: 0.1  # Sample 10% of requests

# Error handling for production
error_handling:
  capture_exceptions: true
  sentry_dsn: "${SENTRY_DSN}"  # From environment
  max_traceback_frames: 10
  
  # Circuit breaker settings
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 60
    expected_exception: "AutoMCPError"

# Resource limits
limits:
  max_file_size: "100MB"
  max_processing_time: 600  # 10 minutes
  max_memory_usage: "2GB"
  max_concurrent_operations: 50
