# =============================================================================
# AutoMCP Production Configuration
# =============================================================================
# Production-optimized settings with strict validation and performance features
# Inherits from default.yaml and overrides for production deployment

environment: "production"
profile: "production"

# =============================================================================
# Production LLM Configuration - Optimized Settings
# =============================================================================
llm_client:
  provider_settings:
    groq:
      max_tokens: 1000      # Optimized for production efficiency
      temperature: 0.1      # Lower temperature for consistent responses
      optimal_batch_size: 16  # Larger batches for production throughput
      rate_limit_requests_per_minute: 120

# =============================================================================
# Production Parser Configuration - High Performance
# =============================================================================
parser_workers: 16
parsers:
  workers: 16
  timeout: 30  # Stricter timeout for production

# =============================================================================
# Production Semantic Transformation - Optimized Prompts
# =============================================================================
semantic_transformation:
  llm_prompts:
    intent_generation: |
      Generate a production-grade semantic intent for this API endpoint:
      Method: {method}
      Path: {path}
      Summary: {summary}
      Domain: {domain_context}

      Required elements:
      1. Clear, business-focused name
      2. Concise yet comprehensive summary
      3. Accurate complexity assessment
      4. Specific user context and permissions
      5. Security requirements with rationale
      6. Clear permission levels with justification
      7. Business impact assessment
      8. Error handling implications

      Format: Structured, consistent, production-ready output

    tool_generation: |
      Create a production-grade MCP tool definition:
      Method: {method}
      Path: {path}
      Parameters: {parameters}
      Domain: {domain_context}

      Required elements:
      1. Production-ready description
      2. Comprehensive safety analysis
      3. Complete parameter validation
      4. Required field validation rules
      5. Performance metadata
      6. Error handling guidance
      7. Rate limiting considerations
      8. Security implications

      Format: Enterprise-ready, validated output

# =============================================================================
# Production Enrichment - Optimized Performance
# =============================================================================
enrichment:
  batch_size: 16
  max_batch_size: 32
  timeout_seconds: 30
  retry_attempts: 3
  use_memory: false

# =============================================================================
# Production Output - Strict Validation
# =============================================================================
output:
  strict_validation: true
  quality_assessment:
    enabled: true
    generate_report: true
    min_acceptable_score: 80  # Higher threshold for production
    use_llm_assessment: true
    sampling_rate: 0.5  # Sample for performance

# =============================================================================
# Production Logging - Structured
# =============================================================================
logging:
  level: INFO
  format: json  # Structured logging for production
  redact_keys:
    - api_key
    - password
    - token
    - secret
    - credential

# =============================================================================
# Production Validation - Strict
# =============================================================================
validation:
  strict: true

# =============================================================================
# Production Security - Enhanced
# =============================================================================
security:
  encrypt_outputs: true  # Enable encryption for production
  input_sanitization: true
  output_encoding: true
  rate_limit_by_key: true

# =============================================================================
# Production Error Handling - Resilient
# =============================================================================
error_handling:
  max_retries: 3
  backoff_strategy: "exponential"
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 60

# =============================================================================
# Production Monitoring - Full Observability
# =============================================================================
monitoring:
  metrics_enabled: true
  health_check_port: 8080
  prometheus_endpoint: "/metrics"
  log_sampling_rate: 0.1
  slow_query_threshold: 5

# =============================================================================
# Production Exporter - API Enabled
# =============================================================================
exporter:
  api_auth: true
  api_port: 8000
