openapi: 3.0.0
info:
  title: Simple Test API
  version: 1.0.0
  description: A simple API for testing the configuration system
servers:
  - url: https://api.example.com/v1
    description: Production server
paths:
  /search:
    get:
      summary: Search for items
      description: Search for items in the system
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: Search query string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Maximum number of results
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        description:
                          type: string
                  total:
                    type: integer
  /items:
    post:
      summary: Create a new item
      description: Create a new item in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
              required:
                - title
      responses:
        '201':
          description: Item created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
